config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: :show # Quitamos la opcion show
  
  # delete '/products/:id', to: 'products#destroy'
  # post '/products', to: 'products#create'
  # patch '/products/:id', to: 'products#update'
  # get '/products/new', to: 'products#new', as: :new_product
  # get '/products/:id/edit', to: 'products#edit', as: :edit_product
  # get '/products', to: 'products#index'
  # get '/products/:id', to: 'products#show', as: :product
  resources :products, path: '/' # Con esto podemos obviar las lineas anteriores al usar la convencion de nombres por defecto de rails, 
                                 # y con path: '/' hacemos que /products resida en /
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products, dependent: :restrict_with_exception # Una categoria tiene varios productos (claves foraneas)

    validates :name, presence: true # El nombre tiene que ser obligatorio, sino podriamos crear categorias sin nombre
end

app/models/product.rb
class Product < ApplicationRecord
    include PgSearch::Model
    pg_search_scope :search_full_text, against: {
        title: 'A',
        description: 'B'
    } # Las letras indican la prioridad en la busqueda

    has_one_attached :photo # Para guardar fotos usamos has_one_attached :nombre_que_queramos

    validates :title, presence: true
    validates :description, presence: true
    validates :price, presence: true

    belongs_to :category # Un producto pertenece a una categoria (claves foraneas)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend

    around_action :switch_locale

    def switch_locale(&action)
        I18n.with_locale(locale_from_header, &action)
    end

    def locale_from_header
        request.env['HTTP_ACCEPT_LANGUAGE']&.scan(/^[a-z]{2}/)&.first
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all.order(name: :asc)
  end

  def new
    @category = Category.new
  end

  def edit
    category
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_url, notice: t('.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if category.update(category_params)
      redirect_to categories_url, notice: t('.updated') 
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    category.destroy

    redirect_to categories_url, notice: t('.destroyed') 
  end

  private
    def category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @categories = Category.all.load_async
        # @products = Product.all.with_attached_photo # Con with_attached_photo evitamos las consultas innecesarias que se hacen a la BD

        # # Filtrado por categorias
        # if params[:category_id]
        #     @products = @products.where(category_id: params[:category_id]) # Extendemos la query anterior
        # end

        # if params[:min_price].present? # Con present? comprobamos que el parametro contiene valor, porque se va enviar aunque este vacio 
        #     @products = @products.where('price >= ?', params[:min_price]) # Aqui el '?' es parecido a PHP
        # end

        # if params[:max_price].present?
        #     @products = @products.where('price <= ?', params[:max_price])
        # end

        # if params[:query_text].present?
        #     @products = @products.search_full_text(params[:query_text])
        # end

        # if params[:order_by].present?
        #     order_by = {
        #         newest: 'created_at DESC',
        #         expensive: 'price DESC',
        #         cheapest: 'price ASC'
        #     }.fetch(params[:order_by]&.to_sym, 'created_at DESC') # Recibimos un string por parametros, con to_sym lo convertimos a simbolo
        #     # order[params[:order_by]] Esto hace los mismo que el fetch anterior, pero el fetch nos ofrece la posibilidad de introducir un valor por defecto (created_at DESC), incluso el bloque IF no seria necesario

        #     @products = @products.order(order_by).load_async # ATENCION: Solo puede haber un order en cada consulta, asegurate de que no tienes ningun order en las consultas anteriores
        #                                                      # Ademas el metodo load_async siempre tiene que ir al final
        # end

        # @pagy, @products = pagy_countless(@products, items: 12)

        # Todo lo anterior lo refactorizamos asi. El archivo esta en app > queries > find_products.rb
        @pagy, @products = pagy_countless(FindProducts.new.call(product_params_index).load_async, items: 12)
    end

    def show
        product
    end

    def new
        @product = Product.new
    end

    def create
        @product = Product.new(product_params)

        if @product.save
            redirect_to products_path, notice: t('.created')
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        product
    end

    def update
        if product.update(product_params) # Aqui quitamos el @ y asi llamamos al metodo producto creado mas abajo y se le aplica el update directamente
            redirect_to products_path, notice: t('.updated')
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        product.destroy # Aqui quitamos el @ y asi llamamos al metodo producto creado mas abajo y se le aplica el destroy directamente

        redirect_to products_path, notice: t('.destroyed'), status: :see_other
    end

    private
    def product_params
        params.require(:product).permit(:title, :description, :price, :photo, :category_id)
    end

    def product_params_index
        params.permit(:category_id, :min_price, :max_price, :query_text, :order_by)
    end

    def product
        @product = Product.find(params[:id]) # En ruby, la ultima sentencia se corresponde con el return
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
    <%= category.name %>

    <%= link_to t('.edit'), edit_category_path(category) %>
    <%= link_to t('.delete'), category_path(category), data:{
    turbo_method: :delete,
    turbo_confirm: t('common.confirm')
} %> 
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% @category.errors.full_messages.each do |error| %>
        <%= error %>
        <br>
    <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render "form", category: @category %>

<div>
  <%= link_to t('common.back'), categories_path %>
</div>

app/views/categories/index.html.erb
<h1><%= t('.title') %></h1>

<%= render partial: 'category', collection: @categories %>

<%= link_to t('.new'), new_category_path %>

app/views/categories/new.html.erb
<h1><%= t('.title') %></h1>

<%= render "form", category: @category %>

<div>
  <%= link_to t('common.back'), categories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('app_name') %> | <%= t('meta_title') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/flash' %>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h2><%= t('.title') %></h2>

<%= render 'shared/form' %>

app/views/products/index.html.erb
<%= turbo_frame_tag 'home' do %>

    <h2><%= t('.title') %></h2>

    <%= form_with url: products_path, method: :get do |form| %>
        <%= form.text_field :query_text, placeholder: t('.query_text'), onChange: 'this.form.requestSubmit()', value: params[:query_text] %>

        <%= form.number_field :min_price, placeholder: t('.min_price'), onChange: 'this.form.requestSubmit()', value: params[:min_price] %> <!-- Con value hacemos que el parametro se quede en la caja y no cambie al hacer la peticion -->
        <%= form.number_field :max_price, placeholder: t('.max_price'), onChange: 'this.form.requestSubmit()', value: params[:max_price] %>

        <%= form.select :order_by, options_for_select([[t('.newest'), 'newest'], [t('.expensive'), 'expensive'], [t('.cheapest'), 'cheapest']], params[:order_by]), {}, { onChange: 'this.form.requestSubmit()' } %> <!-- El options_for_select tiene varias formas de pasar los valores, consultalas en la documentacion -->
    <% end %>

    <%= link_to t('.all'), products_path %>

    <%= render partial: 'shared/category', collection: @categories %>

    <%= turbo_frame_tag "products-#{@pagy.page}", class: 'products' do %> <!-- CUIDADO: hay que usar las comillas dobles -->
        <%= render partial: 'shared/product', collection: @products %> <!-- En el partial ponemos lo que habia dentro del bucle, y esto ya genera el bucle automaticamente con collection -->
        <%= turbo_frame_tag "products-#{@pagy.next}", class: 'products', src: pagy_url_for(@pagy, @pagy.next), loading: :lazy if @pagy.next %> <!-- Hacemos la paginacion infinita. Con el if, nos evitamos la ultima peticion a una pagina que no existe -->
    <% end %>

<% end %>

app/views/products/new.html.erb
<h2><%= t('.title') %></h2>

<%= render 'shared/form' %>

app/views/products/show.html.erb
<br>

<%= image_tag @product.photo, width: 200 if @product.photo.attached? %>

<h1 class='title'><%= @product.title %></h1>

<p class='description'><%= @product.description %></p>

<span class='price'><%= @product.price %>$</span><br>

<%= link_to 'Editar producto', edit_product_path(@product) %><br>

<%= link_to 'Eliminar producto', product_path(@product), data:{
    turbo_method: :delete,
    turbo_confirm: t('common.confirm')
} %>  <!-- Por defecto los link_to hacen peticiones GET, debemos cambiarlo -->

app/views/shared/_category.html.erb
<%= link_to products_path(category_id: category.id), class: 'category' do %>
    <%= category.name %>
<% end %>

app/views/shared/_flash.html.erb
<%= notice %>

<%= alert %>

app/views/shared/_form.html.erb
<%= form_with model: @product do |form| %>
    <% @product.errors.full_messages.each do |error| %>
        <%= error %>
        <br>
    <% end %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div>
        <%= form.label :description %>
        <%= form.text_area :description %>
    </div>

    <div>
        <%= form.label :category_id %>
        <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name %> 
    </div>

    <div>
        <%= form.label :price %>
        <%= form.number_field :price %>
    </div>

    <div>
        <%= form.label :photo %>
        <%= form.file_field :photo %>
    </div>

    <%= form.submit %>
<% end %>

app/views/shared/_header.html.erb
<%= link_to products_path() do %>
    <h1><%= t('app_name') %></h1>
<% end %>

<%= link_to t('.add'), new_product_path() %>

<%= link_to t('.categories'), categories_path() %>

app/views/shared/_product.html.erb
<%= link_to product_path(product.id), class: 'product', 'data-turbo-frame': '_top' do  %> <!-- Con 'data-turbo-fram'... hacemos que se salga del frame y no haya ningun bug --> 
    <br>
    <%= image_tag product.photo, width: 200 if product.photo.attached? %> <!-- Con if product.photo.attached? comprobamos si tiene una foto adjunta -->
    <h2><%= product.title %></h2>
    <span><%= product.price %>$</span>
<% end %>